version: '2'
services:
  app:
    build: .
    volumes:
      - .:/src
    network_mode: "bridge"
    ports:
     - "8080:8080"
    environment:
      CONFIG_PATH:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_REGION: eu-west-1
